import json
from datetime import datetime
from pathlib import Path

# Dynamically calculate the log file path
BASE_DIR = Path(__file__).resolve().parent.parent.parent
LOG_FILE = BASE_DIR / "backend" / "data" / "forensic_audit.log"

# Ensure the log directory exists
LOG_FILE.parent.mkdir(parents=True, exist_ok=True)

def log_audit_event(session_id: str, prompt: str, generated_sql: str = None, success: bool = True, error_message: str = None):
    """
    Constructs a structured JSON log entry and writes it to the audit log file.

    Args:
        session_id: The unique identifier for the user's session.
        prompt: The original user prompt.
        generated_sql: The SQL query generated by the LLM, if any.
        success: A boolean indicating if the overall operation was successful.
        error_message: The error message if the operation failed.
    """
    # Construct the log entry dictionary
    log_entry = {
        "timestamp": datetime.utcnow().isoformat(),
        "session_id": session_id,
        "prompt": prompt,
        "generated_sql": generated_sql,
        "status": "SUCCESS" if success else "FAILURE",
        "error_message": error_message,
    }

    # Open the log file in append mode and write the JSON entry
    with open(LOG_FILE, "a") as f:
        f.write(json.dumps(log_entry) + "\n")
