import sqlglot
from sqlglot.errors import ParseError

def sanitize_and_validate_sql(raw_sql: str) -> str:
    """
    Parses a raw SQL string to ensure it only contains SELECT statements.
    
    Args:
        raw_sql: The SQL string generated by the LLM.
        
    Returns:
        A sanitized, formatted SQL string if it is a valid SELECT query.
        
    Raises:
        ValueError: If the SQL is malformed or contains non-SELECT operations.
    """
    try:
        # Parse the raw SQL, supporting the SQLite dialect.
        parsed_statements = sqlglot.parse(raw_sql, read="sqlite")
        
        if not parsed_statements:
            raise ValueError("The AI generated an empty SQL query.")
            
        # Iterate through all statements found in the query string.
        for statement in parsed_statements:
            # Check if the statement is a SELECT query.
            if not isinstance(statement, sqlglot.exp.Select):
                # If any statement is not a SELECT, reject the entire query.
                raise ValueError("Unauthorized SQL operation detected. Only SELECT statements are permitted.")
                
        # If all statements are valid, re-compile the first one to a clean string.
        return parsed_statements[0].sql(dialect="sqlite")
        
    except ParseError:
        # If sqlglot cannot parse the SQL, it's malformed.
        raise ValueError("The AI generated malformed SQL syntax.")
